--- #YAML:1.0
name:                Script-Toolbox
version:             0.29
abstract:            Framework for the daily business scripts
license:             ~
author:              
    - Matthias Eckardt <www.link-up.de>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Data::Dumper:                  2
    Fatal:                         1
    File::stat:                    1
    IO::Dir:                       1
    IO::File:                      1
    Time::ParseDate:               1
    UNIVERSAL:                     1
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
